# Generated by Django 4.0.1 on 2022-02-03 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloon', '0003_alter_saloon_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Categoria de oferta',
                'verbose_name_plural': 'Categorias de ofertas',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='InformativeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='resumen')),
                ('content', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
                ('last_modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la ultima modificación')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('url', models.SlugField(max_length=256, unique=True)),
                ('email_info', django_quill.fields.QuillField()),
                ('city', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ciudad')),
                ('enable_inscription', models.BooleanField(default=False, verbose_name='Habilitar inscripción')),
                ('exhausted', models.BooleanField(default=False, verbose_name='Agotado')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.offercategory', verbose_name='Categoria')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.saloon', verbose_name='Camara')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.topic', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'BaseTextModel',
                'verbose_name_plural': 'BaseTextModel',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Fecha de creación')),
                ('hours', models.CharField(max_length=256, verbose_name='Hora')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.informativeoffer', verbose_name='Oferta formativa')),
            ],
            options={
                'verbose_name': 'Fecha de realizacion',
                'verbose_name_plural': 'Fechas de realizacion',
            },
        ),
    ]
