# Generated by Django 4.0.1 on 2022-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativeoffer',
            name='duration',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Duracion'),
        ),
    ]
