# Generated by Django 4.0.1 on 2022-06-26 21:04

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_offercategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativeoffer',
            name='due_date',
            field=models.DateField(default=timezone.now, verbose_name='Fecha cuando se cierra la inscripcion'),
            preserve_default=False,
        ),
    ]
