# Generated by Django 4.0.1 on 2022-07-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_informativeoffer_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterealization',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='training.informativeoffer', verbose_name='Oferta formativa'),
        ),
    ]
