# Generated by Django 4.0.1 on 2022-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_daterealization_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativeoffer',
            name='use_in_home',
            field=models.BooleanField(default=False, verbose_name='Usar en la pagina principal'),
        ),
    ]
