# Generated by Django 4.0.1 on 2022-12-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_offercategory_image_backgroud'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativeoffer',
            name='banner_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Banner Home (1300x480px)'),
        ),
    ]
