# Generated by Django 4.0.1 on 2023-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_informativeoffer_banner_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativeoffer',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Imagen'),
        ),
    ]
