# Generated by Django 4.0.1 on 2023-08-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_informativeoffer_in_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNITCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'SNIT',
                'verbose_name_plural': 'SNIT',
            },
        ),
        migrations.CreateModel(
            name='SNITFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('snit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='training.snitcategory', verbose_name='SNIT')),
            ],
            options={
                'verbose_name': 'Archivo SNIT',
                'verbose_name_plural': 'Archivos SNIT',
            },
        ),
    ]
