# Generated by Django 4.0.1 on 2023-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_snitcategory_snitfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snitcategory',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snitfile',
            name='file',
            field=models.FileField(default='', upload_to='', verbose_name='Archivo'),
            preserve_default=False,
        ),
    ]
