version: '3'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/static
      - web-media:/media
    env_file: .env
    command: /usr/local/bin/gunicorn faatra.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./faatra/static:/www/static
      - web-media:/www/media
      - $PWD/faatra.key:/etc/nginx/certs/faatra.key
      - $PWD/faatra.crt:/etc/nginx/certs/faatra.crt
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
  worker:
    restart: always
    build: .
    expose:
      - "8001"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/static
      - web-media:/media
    env_file: .env
    command: celery -A faatra worker -l INFO   

volumes:
  web-django:
  web-static:
  web-media:
  pgdata:
  redisdata:
