# Generated by Django 4.0.1 on 2022-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='', max_length=512, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
