# Generated by Django 4.0.1 on 2022-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.SlugField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
