# Generated by Django 4.0.1 on 2022-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='last_modification_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la ultima modificación'),
        ),
    ]
