# Generated by Django 4.0.1 on 2022-02-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_last_modification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
    ]
