# Generated by Django 4.0.1 on 2023-02-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='service.service'),
        ),
    ]
