# Generated by Django 4.0.1 on 2023-09-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_files_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='  ', max_length=255, verbose_name='Nombre del archivo'),
        ),
    ]
