# Generated by Django 4.0.1 on 2022-02-03 14:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, verbose_name='Fecha de creación')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.CharField(max_length=256, verbose_name='resumen')),
                ('content', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
                ('last_modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la ultima modificación')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('url', models.SlugField(max_length=256, unique=True)),
                ('complete_name', models.CharField(max_length=512, verbose_name='Nombre completo')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('address', models.CharField(max_length=512, verbose_name='Direccion')),
                ('city', models.CharField(max_length=512, verbose_name='Ciudad')),
                ('hours', models.CharField(max_length=512, verbose_name='Horario')),
                ('phone', models.CharField(max_length=512, verbose_name='Telefono')),
                ('web', models.CharField(max_length=512, verbose_name='Web')),
                ('email', models.CharField(max_length=512, verbose_name='E-mail')),
                ('facebook', models.CharField(max_length=512, verbose_name='Facebook')),
                ('reference', models.BooleanField(default=False, verbose_name='Referente')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
            },
        ),
    ]
