# Generated by Django 4.0.1 on 2022-02-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='email',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='hours',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='phone',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='web',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Web'),
        ),
    ]
