# Generated by Django 4.0.1 on 2022-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0005_importantagreement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantagreement',
            name='url',
            field=models.CharField(max_length=256, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=256, verbose_name='URL'),
        ),
    ]
