# Generated by Django 4.0.1 on 2023-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0006_alter_importantagreement_url_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantagreement',
            name='image',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
