# Generated by Django 4.0.1 on 2022-02-03 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0003_alter_informativeoffer_options_and_more'),
        ('saloon', '0006_alter_importantagreement_url_alter_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('video', models.CharField(max_length=256, verbose_name='video')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='resumen')),
                ('content', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen')),
                ('last_modification_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la ultima modificación')),
                ('is_available', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('url', models.SlugField(max_length=256, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.informativeoffer', verbose_name='Curso')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.saloon', verbose_name='Camara')),
            ],
            options={
                'verbose_name': 'Novedades',
                'verbose_name_plural': 'Novedades',
            },
        ),
    ]
