# Generated by Django 4.0.1 on 2022-02-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_informativeoffer_options_and_more'),
        ('saloon', '0006_alter_importantagreement_url_alter_link_url'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.informativeoffer', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='new',
            name='saloon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saloon.saloon', verbose_name='Camara'),
        ),
    ]
