# Generated by Django 4.0.1 on 2023-02-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_new_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_date',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
    ]
