# Generated by Django 4.0.1 on 2023-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_date',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
    ]
