# Generated by Django 4.0.1 on 2022-04-01 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloon', '0006_alter_importantagreement_url_alter_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Nombre y appelido')),
            ],
        ),
        migrations.CreateModel(
            name='Incription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fullname', models.CharField(max_length=512, verbose_name='Nombre y appelido')),
                ('email', models.EmailField(max_length=512, verbose_name='email')),
                ('telefono', models.CharField(max_length=512, verbose_name='Telefono')),
                ('dni', models.CharField(max_length=512, verbose_name='DNI')),
                ('birth_date', models.CharField(max_length=512, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(max_length=512, verbose_name='Direccion')),
                ('zip_code', models.CharField(max_length=512, verbose_name='CP')),
                ('city', models.CharField(max_length=512, verbose_name='Ciudad')),
                ('county', models.CharField(max_length=512, verbose_name='Provincia')),
                ('course', models.CharField(max_length=512, verbose_name='Curso')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('employee_condition', models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='incriptions.employeecondition', verbose_name='Condicion laboral')),
                ('saloon', models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='saloon.saloon', verbose_name='Camara')),
            ],
        ),
    ]
