# Generated by Django 4.0.1 on 2022-04-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_informativeoffer_options_and_more'),
        ('incriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecondition',
            options={'verbose_name': 'Cond. Laboral', 'verbose_name_plural': 'Cond. Laborales'},
        ),
        migrations.AlterModelOptions(
            name='incription',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='incription',
            name='course',
            field=models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='training.informativeoffer', verbose_name='Curso'),
        ),
    ]
