# Generated by Django 4.0.1 on 2022-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incriptions', '0002_alter_employeecondition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incription',
            name='fullname',
            field=models.CharField(max_length=512, verbose_name='Nombre y apellido'),
        ),
    ]
