# Generated by Django 4.0.1 on 2022-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incriptions', '0004_alter_incription_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incription',
            name='birth_date',
            field=models.CharField(max_length=512, verbose_name='Fecha de nacimiento'),
        ),
    ]
