# Generated by Django 4.0.1 on 2022-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incriptions', '0006_remove_incription_saloon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecondition',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Nombre'),
        ),
    ]
