# Generated by Django 4.0.1 on 2022-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsp', models.CharField(max_length=1024, verbose_name='Dirección')),
                ('youtube', models.CharField(max_length=1024, verbose_name='Número de contacto')),
                ('twitter', models.CharField(max_length=1024, verbose_name='Email de contacto')),
                ('instagram', models.CharField(max_length=1024, verbose_name='Horario de atencion')),
                ('facebook', models.CharField(max_length=1024, verbose_name='Horario de atencion')),
                ('linkedin', models.CharField(max_length=1024, verbose_name='Horario de atencion')),
            ],
            options={
                'verbose_name': 'Faatra redes sociales configuraciónes',
            },
        ),
    ]
