# Generated by Django 4.0.1 on 2022-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_siteconfiguration_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaconfiguration',
            name='snit_description',
            field=models.TextField(default='', max_length=1024, verbose_name='Descripcion de SNIT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediaconfiguration',
            name='snit_url',
            field=models.TextField(default='', max_length=1024, verbose_name='Link a SNIT'),
            preserve_default=False,
        ),
    ]
