# Generated by Django 4.0.1 on 2022-07-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_whoweare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoweare',
            name='icon',
        ),
    ]
