# Generated by Django 4.0.1 on 2022-12-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icono'),
        ),
    ]
