# Generated by Django 4.0.1 on 2022-12-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pages_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Icono'),
        ),
    ]
