# Generated by Django 4.0.1 on 2023-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pages_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='use_in_home',
            field=models.BooleanField(default=False, verbose_name='Usar en pagina princial'),
        ),
    ]
