# Generated by Django 4.0.1 on 2023-02-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pages_use_in_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('description', models.CharField(max_length=256, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pages', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
