# Generated by Django 4.0.1 on 2023-02-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='home.pages', verbose_name='Página'),
        ),
    ]
