# Generated by Django 4.0.1 on 2023-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profiles_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='subtitle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Sub titulo'),
        ),
    ]
